### ISSUE TITLE
Release version 4.0.0

### ISSUE THREAD

**Issue by darylldoyle** [10up/wp-local-docker-v2#340]
## Milestone
https://github.com/10up/wp-local-docker-v2/milestone/12

## Release Steps
- [ ] Branch: Starting from `develop`, cut a release branch named `release/4.0.0` for your changes.
- [ ] Version bump: Bump the version number in `package.json`, `package-lock.json`, and any other relevant files if it does not already reflect the version being released.
- [ ] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [ ] Props: update `CREDITS.md` file with any new contributors, confirm maintainers are accurate.
- [ ] Readme updates: Make any other readme changes to `README.md` as necessary.
- [ ] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `master` (`git checkout master && git merge --no-ff develop`). `master` contains the stable development version.
- [ ] Push: Push your master branch to GitHub (e.g. `git push origin master`).
- [ ] Release: Create a [new release](https://github.com/10up/wp-local-docker-v2/releases/new), naming the tag and the release with the new version number, and targeting the `master` branch. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the [milestone](https://github.com/10up/wp-local-docker-v2/milestone/12?closed=1).
- [ ] Close milestone: Edit the [milestone](https://github.com/10up/wp-local-docker-v2/milestone/12) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close the milestone.
- [ ] Punt incomplete items: If any open issues or PRs which were milestoned for `4.0.0` do not make it into the release, update their milestone to `4.0.1`, `4.1.0`, `5

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

.0.0` or `Future Release`.
- [ ] Update [NPM](https://www.npmjs.com/package/wp-local-docker) with the latest version.

**Comment by darylldoyle** [comment]
The release is out, closing.

https://github.com/10up/wp-local-docker-v2/releases/tag/v4.0.0
